echo Compiling...
javac -classpath .:/run_dir/junit-4.12.jar:target/dependency/* -d . AsciiArt/src/AsciiArt.java AsciiArt/src/ReadVideo.java
echo Done
echo Running...
java -classpath .:/run_dir/junit-4.12.jar:target/dependency/* AsciiArt